# IMPORTANT: Changer toutes les valeurs avant d'appliquer !
# Les clés MERCURE_*_JWT_KEY doivent être identiques à MERCURE_JWT_SECRET
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cartes113
type: Opaque
stringData:
  APP_SECRET: "ChangeThisAppSecret32CharsMinimum!"
  DATABASE_URL: "postgresql://app:ChangeMe_PostgresPassword!@postgres:5432/app?serverVersion=15&charset=utf8"
  MERCURE_JWT_SECRET: "ChangeThisMercureHubJWTSecretKey!"
  # Ces deux clés doivent avoir la même valeur que MERCURE_JWT_SECRET
  MERCURE_PUBLISHER_JWT_KEY: "ChangeThisMercureHubJWTSecretKey!"
  MERCURE_SUBSCRIBER_JWT_KEY: "ChangeThisMercureHubJWTSecretKey!"
  SENTRY_DSN: ""
