# IMPORTANT: Changer toutes les valeurs avant d'appliquer !
# Les clés MERCURE_*_JWT_KEY doivent être identiques à MERCURE_JWT_SECRET
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cartes113
type: Opaque
stringData:
  APP_SECRET: "6d20d713105924958ac11bba8082a17fa3c61c9a2a739745c4eb67634de164a3"
  DATABASE_URL: "postgresql://app:5PDn27ZZL1TtcJfHZnpW@postgres:5432/app?serverVersion=15&charset=utf8"
  MERCURE_JWT_SECRET: "f2qAaBrZGwVa9UjixOXpi9FjPsDJ5xvT7GXDyWbj3bPGiKjRI57+uM9A6CU3UN2o"
  # Ces deux clés doivent avoir la même valeur que MERCURE_JWT_SECRET
  MERCURE_PUBLISHER_JWT_KEY: "f2qAaBrZGwVa9UjixOXpi9FjPsDJ5xvT7GXDyWbj3bPGiKjRI57+uM9A6CU3UN2o"
  MERCURE_SUBSCRIBER_JWT_KEY: "f2qAaBrZGwVa9UjixOXpi9FjPsDJ5xvT7GXDyWbj3bPGiKjRI57+uM9A6CU3UN2o"
  SENTRY_DSN: ""
