# IMPORTANT: Changer toutes les valeurs avant d'appliquer !
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cartes113
type: Opaque
stringData:
  APP_SECRET: "6d20d713105924958ac11bba8082a17fa3c61c9a2a739745c4eb67634de164a3"
  DATABASE_URL: "postgresql://app:5PDn27ZZL1TtcJfHZnpW@postgres:5432/app?serverVersion=15&charset=utf8"
  SENTRY_DSN: ""
