apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cartes113
data:
  # Symfony
  APP_ENV: "prod"
  TRUSTED_PROXIES: "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  TRUSTED_HOSTS: "^fs-cartes113\\.forelse\\.info$"
  CORS_ALLOW_ORIGIN: "^https://fs-cartes113\\.forelse\\.info$"

  # Caddy
  # :80 → Traefik gère le TLS, Caddy sert en HTTP
  SERVER_NAME: ":80"
  CADDY_DEBUG: ""
  # PWA_UPSTREAM : si pas de frontend Next.js, laisser tel quel (requêtes HTML → PHP)
  PWA_UPSTREAM: ""
