apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: cartes113
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: app-data
  resources:
    requests:
      storage: 10Gi
